### ISSUE TITLE
File field in v1.7.24 only shows images

### ISSUE THREAD

**Issue by tmconnect** [funkjedi/acf-qtranslate#122]
As the title says the File field only shows images in the media uploader.

If I upload a zip-file, the file is uploaded but not displayed to be selected. The same with previous uploaded files, which are all shown in standard ACF File field.

**Comment by mac801** [comment]
Got same problem with PDF files. They get uploaded to main Media Library although only images are available when you want to pick file for ACF File field.

**Comment by mayaliny** [comment]
hey @funkjedi i have this very problem and i think it's related with a js error thrown with repeater fields..

they are discussing it here https://github.com/qtranslate/qtranslate-xt/issues/613 

also if you don't know qtranslate-xt is the community edition of the abandoned qtranslate.. acf-qtranslate should be compatible with that and start to work together with @herrvigg since qtranslatex is outdated and not fully compatible with newer wordpress versions.

**Comment by herrvigg** [comment]
Apart from resurrecting the project one thing i'm doing at the moment is trying to merge some of the separate add-on plugins into the main project as add-on modules. Imo it should be easier to handle like this, for now and for the evolutions to come.
At the moment the main drawback is that the qTranslate-XT is a kind of transition project, it might change name in the future but i want to put it on right tracks so that we and the community can make it live. So for now it's only distributed through github. About ACF if people are available for experiments i can setup a specific branch or i can try to give a hand for some specific questions.

**Comment by mayaliny** [comment]
FYI I opened an issue on main ACF support forum for this problem with the "File field" media gallery showing only "images" and not all the choices in the normal media gallery.

https://support.advancedcustomfields.com/forums/topic/incomplete-media-gallery-options-in-file-field/

(this seems to be unrelated from the issue with js problem i mentioned before)

**Comment by mayaliny** [comment]
I found that the problem is with fields that are "type": "qtranslate_file" (this is an extract from the json export), changing them back to standard "file" solves the problem (but make you unable to link different files in different languages)

So yes this is a ACF QTranslate issue @funkjedi

**Comment by funkjedi** [comment]
Just released new version (v1.7.25) with fix.

**Comment by tmconnect** [comment]
Thanks for the fix
