### ISSUE TITLE
Post does'nt save/update after clicking on any language tab, ACF 5, works with ACF4

### ISSUE THREAD

**Issue by devil1991** [funkjedi/acf-qtranslate#15]

**Comment by pepodebu** [comment]
Hello, I'm having similar issues here. Is there any workaround for this? Thank you very much!

**Comment by petehobo** [comment]
I've got the same problem.  Looking at the network console, the validation is initially being called multiple times (once per language?), which seems to result in an infinite series of calls to `admin-ajax.php` (with the `acf/validate_save_post` parameter).

As others have noted, this only happens when I change languages before submitting (I can change the value for the default language and submit without an issue).

In my particular case, I'm not using WYSIWYG fields, and I've found if I comment out the `acf.do_action('ready', parent.parents('.acf-field'));` line in `v5/assets/input.js`, things work as expected.  It stops WYSIWYG fields working, but that's not currently a problem for me.

I'm using the latest ACF pro (v5.1.5), ACF qTranslate (v1.4), mqTranslate (v2.9.1.2) and WordPress (v4.1).  Happy to help with further investigation, as I expect I'll be using WYSIWYG fields soon enough.

**Comment by alancwoo** [comment]
Wanted to mention, I was only able to get this to work by commenting ALL WYSIWYG related code, so basically everything below line 31: https://github.com/funkjedi/acf-qtranslate/blob/master/v5/assets/input.js#L31-L370

Obviously not ideal but I am in the lucky situation of also not requiring WYSIWYG fields at this stage, but would really love to find a solution to this eventually. Find it a bit strange this is occurring as I don't even have any WYSIWYG fields on this page anyhow.

ACF Pro 5.1.8
ACF qTranslate 1.4
mqTranslate 2.9.1.2

**Comment by funkjedi** [comment]
These issues have been cleared up in the latest version.
